### ISSUE TITLE
Update list of actively maintained plasma implementations

### ISSUE THREAD

**Issue by kfichter** [ethsociety/learn-plasma#103]
The current list of implementations on `/build` is a little stale. I figure we can remove the ones that haven't been touched in 3+ months and add any new implementations that have popped up since!

**Comment by kfichter** [comment]
@therevoltingx Is https://github.com/luciditytech/lucidity-plasma still actively maintained?

**Comment by therevoltingx** [comment]
@kfichter 

Hmm, kinda not really at this point. We're focusing on Plasma Cash because it uses some concepts that we use in our own system (which we call Plasma Bank.)

We do plan on using Plasma MVP style exits and using it as a library but we're not quite there yet.

Ideally we'd want to collab on a repo that's shared and more community driven so we don't create our own version. Then we want to be able to use it as libraries within our own products and smart contracts.

**Comment by kfichter** [comment]
Cool, makes sense. Will remove it from this as I want to point people to places they can go to help out and get help. We should chat a community implementation later this month if you're around.

**Comment by therevoltingx** [comment]
Sounds good to me! Yeah let's chat later about co-ordinating those efforts.
